Repository rl-institut/digiplan, pull requests merged in 2023-10, with the labels that each got.

#378 Fix/#375 complete thermal storages params
  CHANGELOG.md
  digiplan/map/forms.py
  digiplan/map/hooks.py
Labels: bug :lady_beetle:

#377 Improve oemof simulation runs
  CHANGELOG.md
  digiplan/static/js/menu.js
  digiplan/static/js/results.js
  poetry.lock
Labels: enhancement :rocket:

#379 Fix/#355 add note on tech requirements to onboarding
  CHANGELOG.md
  digiplan/static/scss/components/_modals.scss
  digiplan/templates/components/onboarding.html
Labels: bug :lady_beetle:, frontend :rainbow:

#383 Fix/#382 heat demand settings esys
  CHANGELOG.md
  digiplan/map/hooks.py
Labels: bug :lady_beetle:
